import type { MentorMethod } from "@/services/mentor-methods/method-types";

export const mentorMethodLibrary: MentorMethod[] = [
  {
    domain: "Life",
    exampleQuestion: "What value do you want this decision to honor most?",
    id: "life-values-clarification",
    mentorInstruction:
      "Reflect the tension first, then help identify one value that can guide the next move without presenting a full values exercise.",
    mentorSlug: "life",
    shortDescription: "Clarify what the user wants a choice to stand for.",
    tags: ["values", "meaning", "choice", "decision", "direction"],
    title: "Values clarification",
    whenToUse: "When the user is choosing between paths or wants meaningful direction.",
  },
  {
    domain: "Life",
    exampleQuestion: "What is one small change that would give you useful information?",
    id: "life-small-experiment",
    mentorInstruction:
      "Validate the uncertainty, then turn the broad change into one reversible real-world experiment rather than asking for a final answer.",
    mentorSlug: "life",
    shortDescription: "Test a direction through one small, reversible experiment.",
    tags: ["stuck", "change", "first", "direction", "uncertain", "experiment"],
    title: "Small life experiment",
    whenToUse: "When the user feels stuck or cannot know the right change in advance.",
  },
  {
    domain: "Life",
    exampleQuestion: "Where have you noticed this pattern most clearly lately?",
    id: "life-pattern-noticing",
    mentorInstruction:
      "Gently name one possible repeated pattern as a hypothesis, keep it non-judgmental, and ground it in the current example.",
    mentorSlug: "life",
    shortDescription: "Notice a recurring pattern without turning it into a verdict.",
    tags: ["pattern", "again", "always", "repeating", "keep", "same"],
    title: "Pattern noticing",
    whenToUse: "When the user describes the same tension, behavior, or outcome recurring.",
  },
  {
    domain: "Life",
    exampleQuestion: "What new information would actually change this decision?",
    id: "life-decision-loop-breaker",
    mentorInstruction:
      "Name the possible analysis loop gently, then offer one bounded decision criterion or reversible step without teaching a full framework.",
    mentorSlug: "life",
    shortDescription: "Interrupt repeated analysis that is no longer producing clarity.",
    tags: ["overthinking", "decision", "decide", "loop", "replaying", "rumination"],
    title: "Decision-loop breaker",
    whenToUse: "When the user keeps circling a decision without gaining information.",
  },
  {
    domain: "ADHD",
    exampleQuestion: "What is the smallest five-minute version of starting this?",
    id: "adhd-five-minute-entry",
    mentorInstruction:
      "Normalize the starting barrier, then offer one visible action that takes about five minutes. Do not add a productivity list.",
    mentorSlug: "adhd",
    shortDescription: "Shrink task entry to one tiny, time-limited action.",
    tags: [
      "avoid",
      "avoiding",
      "start",
      "starting",
      "opening",
      "impossible",
      "procrastination",
      "task initiation",
    ],
    title: "Five-minute task entry",
    whenToUse: "When the user knows what matters but cannot begin.",
  },
  {
    domain: "ADHD",
    exampleQuestion: "What is making the first move harder than it needs to be?",
    id: "adhd-friction-scan",
    mentorInstruction:
      "Reflect the executive-function friction without blame, identify one obstacle, and remove or reduce that obstacle before asking for effort.",
    mentorSlug: "adhd",
    shortDescription: "Find and reduce one source of friction before starting.",
    tags: ["friction", "blocked", "hard", "avoidance", "setup", "unclear", "overwhelmed"],
    title: "Task friction scan",
    whenToUse: "When setup, ambiguity, or environment is blocking task entry.",
  },
  {
    domain: "ADHD",
    exampleQuestion: "Would another person’s quiet presence make starting easier?",
    id: "adhd-body-doubling",
    mentorInstruction:
      "Suggest one realistic form of co-presence or check-in, framed as external support rather than dependence or moral accountability.",
    mentorSlug: "adhd",
    shortDescription: "Use light co-presence to support initiation and sustained attention.",
    tags: ["alone", "accountability", "body double", "body doubling", "cowork", "check-in"],
    title: "Body doubling",
    whenToUse: "When attention or initiation is harder while working alone.",
  },
  {
    domain: "ADHD",
    exampleQuestion: "Where can the next action stay visible outside your head?",
    id: "adhd-externalize-next-action",
    mentorInstruction:
      "Acknowledge the working-memory load, then put only the immediate next action in one visible place. Avoid building a complex system.",
    mentorSlug: "adhd",
    shortDescription: "Move the immediate next action out of working memory.",
    tags: ["forget", "scattered", "working memory", "out of sight", "visible", "too much in my head"],
    title: "Externalize the next action",
    whenToUse: "When the user is mentally juggling tasks or losing the next step.",
  },
  {
    domain: "Relationship",
    exampleQuestion: "What usually happens just before the argument accelerates?",
    id: "relationship-conflict-cycle-map",
    mentorInstruction:
      "Stay balanced, name one possible interaction cycle rather than blaming either person, and locate the earliest point where the cycle could change.",
    mentorSlug: "relationship",
    shortDescription: "Map the repeating interaction sequence beneath an argument.",
    tags: ["arguing", "argument", "escalates", "escalating", "conflict", "same fight", "defensive"],
    title: "Conflict cycle map",
    whenToUse: "When small disagreements repeatedly escalate into the same conflict.",
  },
  {
    domain: "Relationship",
    exampleQuestion: "How could you open this without blame while still being honest?",
    id: "relationship-soft-start",
    mentorInstruction:
      "Help shape one calm opening that describes the moment and the user's experience without accusation. Do not script a long speech.",
    mentorSlug: "relationship",
    shortDescription: "Begin a difficult conversation clearly and without blame.",
    tags: ["conversation", "talk", "say", "blame", "defensive", "bring up", "communicate"],
    title: "Soft conversation start",
    whenToUse: "When the user needs to raise a concern without triggering immediate defense.",
  },
  {
    domain: "Relationship",
    exampleQuestion: "What do you most want them to understand or respond to?",
    id: "relationship-need-request-translation",
    mentorInstruction:
      "Translate one complaint into the underlying need and one specific request, while respecting that the other person may answer differently.",
    mentorSlug: "relationship",
    shortDescription: "Turn criticism into one honest need and workable request.",
    tags: ["need", "request", "never", "always", "listen", "understand", "ignored"],
    title: "Need-to-request translation",
    whenToUse: "When the user's concern is coming out as criticism or a global complaint.",
  },
  {
    domain: "Relationship",
    exampleQuestion: "What small repair would feel genuine rather than performative?",
    id: "relationship-repair-attempt",
    mentorInstruction:
      "Validate the hurt, then identify one accountable repair attempt. Do not pressure reconciliation or minimize safety concerns.",
    mentorSlug: "relationship",
    shortDescription: "Choose one accountable action after disconnection or conflict.",
    tags: ["repair", "apologize", "apology", "hurt", "barely speaking", "distance", "after fight"],
    title: "Repair attempt",
    whenToUse: "When conflict has ended but connection or accountability needs repair.",
  },
  {
    domain: "Stress / Burnout",
    exampleQuestion: "What demand is consuming the most capacity right now?",
    id: "stress-capacity-triage",
    mentorInstruction:
      "Validate that the system is over capacity, then identify the single demand creating the most load instead of adding coping tasks.",
    mentorSlug: "stress-burnout",
    shortDescription: "Identify the largest current demand before adding solutions.",
    tags: ["overloaded", "overload", "too much", "exhausted", "capacity", "resent", "everything"],
    title: "Capacity triage",
    whenToUse: "When many demands have merged into undifferentiated overload.",
  },
  {
    domain: "Stress / Burnout",
    exampleQuestion: "What could be removed, delayed, or renegotiated first?",
    id: "stress-demand-boundary",
    mentorInstruction:
      "Reflect the pressure, then choose one demand to remove, delay, or renegotiate. Do not imply that better self-management solves an unsafe workload.",
    mentorSlug: "stress-burnout",
    shortDescription: "Reduce load through one concrete boundary or renegotiation.",
    tags: ["boundary", "workload", "deadline", "say no", "guilty", "stop working", "pressure"],
    title: "Demand boundary",
    whenToUse: "When recovery is undermined by an unchanged or unsafe level of demand.",
  },
  {
    domain: "Stress / Burnout",
    exampleQuestion: "What kind of rest has actually felt restorative lately?",
    id: "stress-recovery-match",
    mentorInstruction:
      "Acknowledge that time off is not automatically restorative, then match one low-pressure recovery action to the user's actual depletion.",
    mentorSlug: "stress-burnout",
    shortDescription: "Match recovery to the kind of depletion the user is experiencing.",
    tags: ["recover", "recovery", "rest", "can't switch off", "depleted", "sleep", "tired"],
    title: "Recovery match",
    whenToUse: "When the user rests but does not feel restored.",
  },
  {
    domain: "Stress / Burnout",
    exampleQuestion: "What would a deliberately lighter return look like?",
    id: "stress-sustainable-reentry",
    mentorInstruction:
      "Support a gradual return with one reduced expectation or protected limit. Avoid turning recovery into another performance target.",
    mentorSlug: "stress-burnout",
    shortDescription: "Return to activity without immediately recreating overload.",
    tags: ["return", "back to work", "routine", "pace", "sustainable", "relapse", "again"],
    title: "Sustainable re-entry",
    whenToUse: "When the user is resuming activity after exhaustion or time away.",
  },
  {
    domain: "Parenting",
    exampleQuestion: "What would help you create one pause before responding next time?",
    id: "parenting-regulate-before-respond",
    mentorInstruction:
      "Validate the pressure without excusing harm, then help the parent create one brief pause before the next response.",
    mentorSlug: "parenting",
    shortDescription: "Create a small pause between parental stress and reaction.",
    tags: ["snapped", "yelled", "angry", "patience", "reacted", "morning rush", "overwhelmed"],
    title: "Regulate before responding",
    whenToUse: "When stress is shortening the gap between feeling and reacting.",
  },
  {
    domain: "Parenting",
    exampleQuestion: "How can you hold the limit while showing that you understand the feeling?",
    id: "parenting-connect-and-boundary",
    mentorInstruction:
      "Pair brief emotional acknowledgment with one clear, age-aware limit. Do not treat empathy as removing the boundary.",
    mentorSlug: "parenting",
    shortDescription: "Combine connection with a clear and consistent boundary.",
    tags: ["boundary", "limit", "tantrum", "won't listen", "rules", "consequence", "conflict"],
    title: "Connect, then hold the boundary",
    whenToUse: "When the parent is choosing between empathy and consistency.",
  },
  {
    domain: "Parenting",
    exampleQuestion: "Where does this routine usually start to fall apart?",
    id: "parenting-routine-friction-scan",
    mentorInstruction:
      "Locate one predictable friction point in the family routine and adjust that point rather than redesigning the whole household.",
    mentorSlug: "parenting",
    shortDescription: "Find one repeatable friction point in a family routine.",
    tags: ["routine", "morning", "bedtime", "school", "rush", "transition", "every day"],
    title: "Family routine friction scan",
    whenToUse: "When the same transition or routine repeatedly creates conflict.",
  },
  {
    domain: "Parenting",
    exampleQuestion: "What simple repair would show accountability and steadiness?",
    id: "parenting-repair-after-rupture",
    mentorInstruction:
      "Make room for guilt, then shape one age-appropriate apology and changed next response without asking the child to comfort the parent.",
    mentorSlug: "parenting",
    shortDescription: "Repair after a parental mistake without collapsing into shame.",
    tags: ["guilty", "apologize", "sorry", "snapped", "yelled", "repair", "tomorrow"],
    title: "Repair after rupture",
    whenToUse: "When the parent regrets a reaction and wants to reconnect responsibly.",
  },
  {
    domain: "Health & Fitness",
    exampleQuestion: "What is the smallest version you could sustain on an ordinary week?",
    id: "health-minimum-viable-routine",
    mentorInstruction:
      "Affirm the wish for consistency, then define one general, non-medical routine minimum that fits ordinary energy rather than an ideal week.",
    mentorSlug: "health-fitness",
    shortDescription: "Set a realistic routine floor for ordinary weeks.",
    tags: ["routine", "sustain", "sustainable", "consistent", "consistency", "habit", "week"],
    title: "Minimum viable routine",
    whenToUse: "When the user's plan only works during unusually motivated weeks.",
  },
  {
    domain: "Health & Fitness",
    exampleQuestion: "What would count as staying connected to the habit today?",
    id: "health-consistency-floor",
    mentorInstruction:
      "Replace the success-or-failure threshold with one modest continuity action. Keep guidance general and body-respectful.",
    mentorSlug: "health-fitness",
    shortDescription: "Protect continuity with a modest definition of showing up.",
    tags: ["stop", "stopped", "skip", "consistency", "follow through", "fall off", "three weeks"],
    title: "Consistency floor",
    whenToUse: "When missing the full plan causes the user to abandon the habit.",
  },
  {
    domain: "Health & Fitness",
    exampleQuestion: "What kind of movement fits the energy you actually have today?",
    id: "health-energy-matched-movement",
    mentorInstruction:
      "Help match general movement intensity to present energy and capacity without prescribing exercise or interpreting symptoms.",
    mentorSlug: "health-fitness",
    shortDescription: "Match movement expectations to current capacity.",
    tags: ["energy", "tired", "low energy", "movement", "workout", "exercise", "capacity"],
    title: "Energy-matched movement",
    whenToUse: "When a fixed plan clashes with the user's current energy or recovery.",
  },
  {
    domain: "Health & Fitness",
    exampleQuestion: "What is one non-punishing way to restart from where you are?",
    id: "health-all-or-nothing-reset",
    mentorInstruction:
      "Name the all-or-nothing cycle gently, remove punishment from the restart, and choose one realistic re-entry action.",
    mentorSlug: "health-fitness",
    shortDescription: "Restart after inconsistency without compensation or shame.",
    tags: ["all or nothing", "punish", "punishing", "restart", "train hard", "fell off", "failed"],
    title: "All-or-nothing reset",
    whenToUse: "When intensity, interruption, and shame are driving a repeated cycle.",
  },
  {
    domain: "Focus",
    exampleQuestion: "If only one outcome moved today, which one would matter most?",
    id: "focus-one-outcome",
    mentorInstruction:
      "Acknowledge the competing priorities, then choose one meaningful outcome without adding a full prioritization framework.",
    mentorSlug: "focus",
    shortDescription: "Choose one outcome to receive real attention now.",
    tags: ["priorities", "priority", "five", "too many", "bouncing", "focus", "what first"],
    title: "One-outcome commitment",
    whenToUse: "When competing priorities are fragmenting attention.",
  },
  {
    domain: "Focus",
    exampleQuestion: "What version of this could you genuinely finish today?",
    id: "focus-finishable-scope",
    mentorInstruction:
      "Reflect why the task is hard to hold, then narrow it to one finishable scope for the available time and energy.",
    mentorSlug: "focus",
    shortDescription: "Narrow a broad task to a realistic finish line.",
    tags: ["finish", "finished", "scope", "too broad", "project", "launch", "part"],
    title: "Finishable scope",
    whenToUse: "When a vague or sprawling task makes sustained attention difficult.",
  },
  {
    domain: "Focus",
    exampleQuestion: "What observable result will count as done enough?",
    id: "focus-define-done",
    mentorInstruction:
      "Make one observable completion condition explicit and protect it from perfectionistic expansion.",
    mentorSlug: "focus",
    shortDescription: "Define the endpoint before work expands indefinitely.",
    tags: ["done", "perfect", "perfection", "endpoint", "complete", "completion", "unclear"],
    title: "Define done",
    whenToUse: "When the user cannot tell where the task ends or keeps expanding it.",
  },
  {
    domain: "Focus",
    exampleQuestion: "Where can the competing thoughts wait while you finish this block?",
    id: "focus-distraction-parking",
    mentorInstruction:
      "Suggest one visible place to capture competing thoughts, then return to the chosen task. Do not build a complex productivity system.",
    mentorSlug: "focus",
    shortDescription: "Capture distractions without following them immediately.",
    tags: ["distracted", "distraction", "interruption", "thoughts", "switching", "bouncing", "attention"],
    title: "Distraction parking place",
    whenToUse: "When unrelated thoughts or interruptions keep pulling attention away.",
  },
  {
    domain: "Charisma",
    exampleQuestion: "What changes when you place your attention on the other person instead of monitoring yourself?",
    id: "charisma-attention-outward-reset",
    mentorInstruction:
      "Teach a brief presence principle, demonstrate an outward-attention cue, then invite a 30-second practice. Ask what the user noticed before setting one low-pressure real-world repetition.",
    mentorSlug: "charisma",
    shortDescription: "Reduce self-monitoring by returning attention to the person and moment.",
    tags: ["presence", "self-conscious", "anxious", "attention", "conversation", "meeting", "dating"],
    title: "Attention outward reset",
    whenToUse: "When self-monitoring makes the user tense, absent, or unable to connect.",
  },
  {
    domain: "Charisma",
    exampleQuestion: "What sincere observation could you pair with one curious follow-up question?",
    id: "charisma-warmth-follow-up",
    mentorInstruction:
      "Explain that warmth is communicated through genuine attention, demonstrate a brief observation-plus-question, then roleplay one exchange and give specific feedback. Avoid canned flattery.",
    mentorSlug: "charisma",
    shortDescription: "Practice warmth through a sincere signal and curious follow-up.",
    tags: ["warmth", "listening", "question", "networking", "opener", "first impression", "conversation"],
    title: "Warmth signal and curious follow-up",
    whenToUse: "When a conversation feels formal, flat, or hard to continue.",
  },
  {
    domain: "Charisma",
    exampleQuestion: "What is the clearest version of your point if you say it once and let it land?",
    id: "charisma-clear-line-pause",
    mentorInstruction:
      "Rewrite the user's point as one concise line, demonstrate where to pause, then have them practice it. Give feedback on clarity, pace, and unnecessary qualifiers rather than personality.",
    mentorSlug: "charisma",
    shortDescription: "Build confident speech with one clear sentence and a deliberate pause.",
    tags: ["voice", "pause", "speaking", "meeting", "interview", "investor", "clarity", "pace"],
    title: "Clear line, then pause",
    whenToUse: "When the user rushes, over-explains, or weakens a useful point with qualifiers.",
  },
  {
    domain: "Charisma",
    exampleQuestion: "What happened, what changed, and why did that moment matter?",
    id: "charisma-moment-change-meaning",
    mentorInstruction:
      "Teach a three-beat story structure, demonstrate it with a short original example, then help the user shape and rehearse their own. Give feedback on specificity, brevity, and natural delivery.",
    mentorSlug: "charisma",
    shortDescription: "Turn an experience into a concise story with a meaningful point.",
    tags: ["story", "storytelling", "social flow", "interview", "networking", "dating", "example"],
    title: "Moment, change, meaning",
    whenToUse: "When the user wants to tell a clearer story without sounding rehearsed or rambling.",
  },
];
